LOGIN_REQUIRED = 'ES NECESARIO INICIAR SESION'

USER_CREATED='USUARIO CREADO EXITOSAMENTE'

LOGIN='USUARIO AUTENTICADO EXITOSAMENTE'
LOGOUT='CERRASTE SESION EXITOSAMENTE'

ERROR_USER_PASSWORD='USUARIO O CONTRASEÑA INCORRECTA'

TASK_GENERATED='TAREA CREADA EXITOSAMENTE'

TASK_UPDATED = 'TAREA EDITADA EXITOSAMENTE'