"""empty message

Revision ID: 44504354f403
Revises: 
Create Date: 2020-05-31 23:56:37.025638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44504354f403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    # ### end Alembic commands ###
